version: "2"
services:
    - mysql:
        image: registry.cn-qingdao.aliyuncs.com/homecommunity/mysql:5.6
        volumes:
            - /home/data/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        extra_hosts: []
        environment:
            - MYSQL_ROOT_PASSWORD:123456
            - --param:--lower_case_table_names=1
            - --param:--max_allowed_packet=900M
